# Get All Albums
GET http://localhost:8080/albums

# Get a Specific Album
GET http://localhost:8080/albums/SOCIWDW12A8C13D406

# Try to get an album which is not available
GET http://localhost:8080/albums/SOCTESTSONG999

#Heroku Test
GET https://whispering-hollows-56519.herokuapp.com/albums

GET https://whispering-hollows-56519.herokuapp.com/albums/SOCIWDW12A8C13D406

