# Get All Albums
GET https://localhost/albums

# Get a Specific Album
GET https://localhost/albums/SOCIWDW12A8C13D406

# Try to get an album which is not available
GET https://localhost/albums/SOCTESTSONG999